FROM ubuntu:18.04

RUN echo ${NEW}
# TO-DO: install gcc g++ boost
RUN apt install gcc \
    g++ \
    libboost-all-dev




# WORKDIR is to change directories for multiple steps to come
#WORKDIR


#COPY

#ENV PYTHONPATH ""
